version: '3'
services:
  central-system:
    build:
      context: ../..
      dockerfile: cs/Dockerfile
    image: ldonini/ocpp1.6-central-system:latest
    container_name: central-system
    environment:
      - SERVER_LISTEN_PORT=8887
    ports:
      - "8887:8887"
    networks:
      - sim
  charge-point:
    build:
      context: ../..
      dockerfile: cp/Dockerfile
    image: ldonini/ocpp1.6-charge-point:latest
    container_name: charge-point
    environment:
      - CLIENT_ID=chargePointSim
      - CENTRAL_SYSTEM_URL=ws://central-system:8887
    networks:
      - sim

networks:
  sim:
    driver: bridge
